from empoweredautoparts.scraping_utility import process_description

# for debugging purposes

html = ['<p><strong><span style="font-size: 24px;">BRAND NEW - GENUINE RDA - </span></strong><strong><span style="font-size: 24px;"><span style="font-size: 24px;">DIMPLED &amp; SLOTTED REAR DISC BRAKE ROTORS + EBC ULTIMAX PREMIUM BRAKE PADS</span></span></strong></p>',
        '<p><span style="font-size: 14px;">These Discs are Genuine Rotors &amp; Drums Australia Pty Ltd items, they include the RDA Factory 12 Months, 20,000Km Warranty.</span></p>',
        '<p><strong><span style="font-size: 14px;">Empowered Auto Parts</span></strong><span style="font-size: 14px;"> additional expertise lies in our ability to get YOU, your order FAST, 95% of the time we use couriers and EXPRESS your item to your door, no hassle, simple and straight forward.</span></p>',
        '<p>\xa0</p>',
        '<p><span style="font-size: 14px;">FORD ESCAPE 2.3L EP3WF EFI 4WD 2003-2006<span style="font-size: 14px;"> DIMPLED &amp; SLOTTED REAR DISC BRAKE ROTORS + BRAKE PADS -</span><em style="font-size: 14px;"> PRODUCT CODES: RDA7669D</em><strong style="font-size: 14px;">(PAIR) </strong><span style="font-size: 14px;">DP1710</span><strong style="font-size: 14px;"> (BRAKE PADS)</strong></span></p>',
        '<p><strong><span style="font-size: 14px;">COMPATIBLE MODELS:</span></strong></p>',
        '<ul>\n<li><span style="font-size: 14px;">FORD ESCAPE 2.3L EP3WF EFI 4WD 2003-2006 REAR </span></li>\n<li><span style="font-size: 14px;">FORD ESCAPE 2.3L XLS ZB &amp; XLT ZB 4WD 11/2005 onwards REAR</span></li>\n<li><span style="font-size: 14px;">FORD ESCAPE LIMITED, XLS, XLT, BA, ZA, ZB 3.0L V6 11/2005 onwards REAR</span></li>\n<li><span style="font-size: 14px;">MAZDA TRIBUTE CU 2.3L EFI 108Kw 4WD 11/2005 onwards REAR </span></li>\n<li><span style="font-size: 14px;">MAZDA TRIBUTE SDX CU 3.0L V6 152Kw 4WD 11/2005 onwards REAR</span></li>\n</ul>',
        '<p><strong><span style="font-size: 14px;">PRODUCT SPECIFICATIONS:</span></strong></p>',
        '<p><span style="font-size: 14px;">DIMPLED &amp; SLOTTED - Solid Type </span></p>',
        '<ul>\n<li><span style="font-size: 14px;">Diameter 302mm</span></li>\n<li><span style="font-size: 14px;">Original Height 56mm</span></li>\n<li><span style="font-size: 14px;">Original Thickness 12mm</span></li>\n<li><span style="font-size: 14px;">Min Thickness ie. Replacement 11mm</span></li>\n<li><span style="font-size: 14px;">Centre Hole 72mm</span></li>\n<li><span style="font-size: 14px;">5 Bolt holes</span></li>\n<li><span style="font-size: 14px;">Rear Fitment</span></li>\n</ul>',
        '<p><span style="font-size: 14px;">These Discs are Genuine Rotors &amp; Drums Australia Pty Ltd items, they include the RDA Factory 12 Months, 20,000Km Warranty.</span></p>',
        '<ul>\n<li><span style="font-size: 14px;">All Brakes and Rotors now come Through with a Black Passivation Finish</span></li>\n<li><span style="font-size: 14px;">Reduced Fitment Times Allowing for a Better Value Product</span></li>\n<li><span style="font-size: 14px;">All Rotors Have a Ground Finish on the Brake Surface, to Enhance Initial Brake Performance</span></li>\n<li><span style="font-size: 14px;">100% of all RDA Brake rotors and Brake Drums are now Dynamic Balanced</span></li>\n</ul>',
        '<p><strong><span style="font-size: 14px;">YOU ARE BUYING:</span></strong></p>',
        '<ul>\n<li><span style="font-size: 14px;">1X REAR Left Rotor</span></li>\n<li><span style="font-size: 14px;">1X REAR Right Rotor</span></li>\n<li><span style="font-size: 14px;">1X REAR Left pair of brake pads</span></li>\n<li><span style="font-size: 14px;">1X REAR Right pair of brake pads</span></li>\n</ul>',
        '<p><span style="font-size: 14px;">Rotors are a direct bolt on item, fitting exactly like the factory items and not needing any other modifications.</span></p>',
        '<p><span style="font-size: 14px;"><strong>Empowered Auto Parts is an Authorised RDA &amp; EBC brakes supplier</strong><strong>, purchasing with us means you have a full extensive Warranty as outlined above. Buying from an un-authorised reseller </strong></span><strong><span style="font-size: 14px;">will compromise your 12 months, 20,000Km warranty..</span></strong></p>',
        '<p><span style="font-size: 11px;">* All Brake products from Rotors &amp; Drums Australia are covered under a extensive 12 months 20,000 Km replacement warranty.The product is not covered when used in off road, competition or club racing purposes and is designed for normal street use only. Parts are not covered if incorrectly fitted.</span></p>',
        '<p><img alt="" class="alignleft" height="75" src="https://www.empoweredautoparts.com.au/assets/images/icon-genuineproduct.png" style="opacity: 1; float: left; margin: 0px 10px 10px 0px;" width="75"><br>\n<br>\n<span style="font-size: 14px;"><strong><u>GENUINE PRODUCT</u></strong> This item is <strong>100% Genuine </strong> and includes the Manufacturers Factory Warranty.</span><br>\n<br>\n<br>\n\xa0</p>',
        '<p><img alt="" class="alignleft" height="75" src="https://www.empoweredautoparts.com.au/assets/images/icon-safety-warning100.png" style="opacity: 1; float: left; margin: 0px 10px 10px 0px;" width="75"><br>\n<span style="font-size: 14px;"><strong><u>SAFETY WARNING</u></strong> As your brake rotor and pads are the most critical components in your vehicles braking system, extreme care must be taken when working on these components and all work should be undertaken by an experienced and capable technician at all times. </span></p>',
        '<p>\xa0</p>',
        '<p><img alt="" class="alignleft" height="75" src="https://www.empoweredautoparts.com.au/assets/images/icon-disclaimer-orange.png" style="opacity: 1; float: left; margin: 0px 10px 10px 0px;" width="75"><br>\n<span style="font-size: 14px;"><strong><u>DISCLAIMER</u></strong> Information given may change at any time before this listing can be updated. Specifications and descriptions are provided by the manufacturers. We offer FREE DELIVERY on all our items purchased. HOWEVER, if you live in remote and regional areas of Australia and freight costs exceed our dedicated freight charge then we will contact you to discuss possible options and if any additional cost may be required to fulfil and complete your order. We thank you in advance for your understanding </span></p>',
        '<p>. <img alt="" class="alignleft" height="75" src="https://www.empoweredautoparts.com.au/assets/images/icon-stock-availability.png" style="opacity: 1; float: left; margin: 0px 10px 10px 0px;" width="75"><br>\n<span style="font-size: 14px;"><strong><u>STOCK AVAILABILITY</u></strong> </span></p>',
        '<p><span style="font-size: 14px;">Although most items are stocked in our Brisbane Logistics warehouse, the shown “Quantity available” does <strong>NOT</strong> reflect Brisbane\'s current stock levels. The shown “Quantity available” reflects the total quantity available from our multiple National warehouse locations, this indicates our national stock on hand and our ability to ship or transfer the product you require from our various warehouses . </span></p>',
        '<p><span style="font-size: 14px;">Therefore, we ask that you be patient as the item you are interested in may require time for our internal stock to transit or ship from Interstate to your selected address. Please check the <strong>“</strong>Estimated delivery time” before you place your order as the status may change without notice.</span></p>',
        '<p><img alt="" class="alignleft" height="75" src="https://www.empoweredautoparts.com.au/assets/images/icon-warranty-orange.png" style="opacity: 1; float: left; margin: 0px 10px 10px 0px;" width="75"><br>\n<span style="font-size: 14px;"><strong><u>WARRANTY</u></strong> All products purchased from The Empowered Group Pty Ltd come with the manufacturer\'s warranty. Your eBay receipt is your proof of purchase for any warranty claim. To find out more about your rights under the Australian Consumer Law, please view our return\'s policy.</span></p>',
        '<p>\xa0</p>',
        '<p><img alt="" class="alignleft" height="75" src="https://www.empoweredautoparts.com.au/assets/images/icon-pickup-orange.png" style="opacity: 1; float: left; margin: 0px 10px 10px 0px;" width="75"><br>\n<span style="font-size: 14px;"><strong><u>ITEM PICKUP</u></strong> Empowered Auto Parts operates from nine (9) logistic centres throughout Australia. You are most welcome to Pickup your item, However pre-purchase must be completed, either online or over the phone. This ensures stock is readily available and that we can prepare the order for your arrival.</span></p>',
        '<p>\xa0</p>']


item = {}
print(process_description(item, html))
